/*
You have been given a generator string ab from which any number of strings can be generated recursively by inserting ‘ab’ at any 
location. You have been given an input string to check if that given string is valid or not.
(i.e. generated by given with given string.) 

eg. 
Input: aabbab 
Output: valid 
Input: abbaab 
Output: Invalid 
*/
public class Main {
    public static void main(String[] args) {
        Main mn = new Main();
        String input1 = "aabbab";
        String input2 = "abbaab";
        System.out.println(input1+" - "+mn.isValid(input1));
     	System.out.println(input2+" - "+mn.isValid(input2));
           
    }
    public boolean isValid(String input)
    {
    	Stack<Character> stck = new Stack<Character>();
    	for(int i=0;i<input.length();i++)
    	{
    		if(input.charAt(i)=='a')
    		{
    			stck.push('a');
    		}
    		else if(input.charAt(i)=='b')
    		{
    			if(stck.isEmpty()||stck.peek()!='a')
    			{
    				return false;
    			}
    			else
    			{
    				stck.pop();
    			}
    		}
    		else
    		{
    			return false;
    		}
    	}
    	return true;
    }
}